version: '3.8'

services:
  cartographie-passive:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - INTERFACE=eth0
      - TIMEOUT=-1
    command: ["./build/cartographie-passive"]
