version: '3.8'

services:
  netprobe:
    container_name: netprobe
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Output:/netprobe/output
    environment:
      - INTERFACE=eth0
      - TIMEOUT=-1
    command: ["./build/netprobe"]
